// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitPull
{
    internal sealed partial class Vsix
    {
        public const string Id = "c71355fb-bd6f-4235-a3b0-0ebaa2bad36f";
        public const string Name = "Git Pull";
        public const string Description = @"Trigger a 'git pull' with a keyboard shortcut or automatically on solution load without having to go through multiple steps in the Team Explorer window.";
        public const string Language = "en-US";
        public const string Version = "1.0.100";
        public const string Author = "Mads Kristensen";
        public const string Tags = "git";
    }
}
