// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitPull
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidGitPullPackageString = "77600ef8-42ac-4bc0-855f-5eecfcd5e5ed";
        public static Guid guidGitPullPackage = new Guid(guidGitPullPackageString);

        public const string guidGitPullAutoloadString = "d23519c8-89dd-46ca-a81b-9297a467d0b0";
        public static Guid guidGitPullAutoload = new Guid(guidGitPullAutoloadString);

        public const string guidGitPullPackageCmdSetString = "de0a4512-f94d-427a-9db1-3957c9ab304e";
        public static Guid guidGitPullPackageCmdSet = new Guid(guidGitPullPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int PullCommandId = 0x0100;
    }
}